name: my_env_name
channels:
  - conda-forge
dependencies:
  - certifi==2019.3.9
  - cryptography==2.6.1
  - entrypoints==0.3
  - Flask==1.0.3
  - itsdangerous==1.1.0
  - jedi==0.13.3
  - Jinja2==2.10.1
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - Keras==2.2.4
  - Markdown==3.1.1
  - notebook==5.7.8
  - numpy==1.16.3
  - pandas==0.24.2
  - plac==0.9.6
  - PyJWT==1.7.1
  - pytest==4.5.0
  - regex==2017.4.5
  - requests==2.22.0
  - SQLAlchemy==1.3.3
  - toolz==0.9.0
  - tornado==6.0.2
  - tqdm==4.31.1
  - urllib3==1.24.3
  - Werkzeug==0.15.2
  - thinc==7.0.4
  - wrapt==1.10.11
  - pip
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_lg
  - pip: 
    - Flask-SQLAlchemy==2.4.0
    - Flask-Uploads==0.2.1
    - spacy==2.1.0
    - torch==1.1.0